name: ignou_notifications
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ignou-logo.jpeg
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
        - asset: assets/fonts/Rubik/Rubik-BlackItalic.ttf
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik/Rubik-BoldItalic.ttf
        - asset: assets/fonts/Rubik/Rubik-ExtraBold.ttf
        - asset: assets/fonts/Rubik/Rubik-ExtraBoldItalic.ttf
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
        - asset: assets/fonts/Rubik/Rubik-LightItalic.ttf
        - asset: assets/fonts/Rubik/Rubik-MediumItalic.ttf
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
        - asset: assets/fonts/Rubik/Rubik-SemiBoldItalic.ttf
